<?xml version="1.0"?>
<package format="3">
  <name>turtle_cpp</name>
  <version>0.0.0</version>
  <description>C++ publisher and subscriber for turtlesim</description>

  <maintainer email="pa31@example.com">pa31</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>turtlesim</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
